### ISSUE TITLE
500 error when logging in

### ISSUE THREAD

**Issue by psycho-baller** [ankitk26/Next-spotify#5]
Hey I was checking out what you did here but when I logged in I get a 500 error and the dashboard is empty

**Comment by ankitk26** [comment]
> Hey I was checking out what you did here but when I logged in I get a 500 error and the dashboard is empty

Hi @psycho-baller, is the error showing up on the hosted website, or did you run it on your local system?

**Comment by ankitk26** [comment]
I have added the documentation for the project in the readme file. Check that out if that may resolve the issue

**Comment by ankitk26** [comment]
> > > Hey I was checking out what you did here but when I logged in I get a 500 error and the dashboard is empty
> > 
> > Hi @psycho-baller, is the error showing up on the hosted website, or did you run it on your local system?
> 
> The hosted website
> <img width="957" alt="image" src="https://user-images.githubusercontent.com/81759594/195865303-d965399b-78f5-4135-b0cd-e1b711dea952.png">
> 

Okay I will check what is causing the error. 
Meanwhile can you let me know if other links are working such as library or liked songs, or is it only on the home page.

**Comment by psycho-baller** [comment]
> 

none of them work for me (all give 500 errors). Best of luck fixing it.

**Comment by psycho-baller** [comment]
Ohh, but isn't that only for development mode? Can't you make it production mode where (supposedly) you don't need an email adress to access the website

**Comment by modyabhi** [comment]
> Ohh, but isn't that only for development mode? Can't you make it production mode where (supposedly) you don't need an email adress to access the website

I don't think this is a production app. If you want to create a production ready app, you need to apply for a quota. Currently in development mode you can specify 25 accounts to test.

**Comment by ankitk26** [comment]
I have applied for the quota. So hoping for acceptance of the request

**Comment by psycho-baller** [comment]
> I have applied for the quota. So hoping for acceptance of the request

nice, hoping for the best

**Comment by oshibka404** [comment]
Oh no, did they elaborate on why they didn't accept the quota request?
